### ISSUE TITLE
Error with rake tasks

### ISSUE THREAD

**Issue by JacquesMarques** [MatUrbanski/todo_api#140]
Hi, I clone this project and try run, but when I try list rake tasks I get this error:

rake -T
rake aborted!
NameError: uninitialized constant Dry::System::Plugins
/Users/jacquesmmarquesicloud.com/RubymineProjects/test/todo_api/system/application.rb:4:in `require'
/Users/jacquesmmarquesicloud.com/RubymineProjects/test/todo_api/system/application.rb:4:in `<top (required)>'
/Users/jacquesmmarquesicloud.com/RubymineProjects/test/todo_api/Rakefile:5:in `require_relative'
/Users/jacquesmmarquesicloud.com/RubymineProjects/test/todo_api/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by MatUrbanski** [comment]
Hi, Please try to hardcode version of `dry-system` gem in your Gemfile:

```
gem 'dry-system', '0.19.1'

```
