### ISSUE TITLE
dry-configurable error

### ISSUE THREAD

**Issue by bl1ndy** [MatUrbanski/todo_api#142]
Hi! An error occurred on any rake task, for example `rake db:migrate --trace`

<details>

```
ArgumentError: wrong number of arguments (given 2, expected 1)
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-configurable-0.16.1/lib/dry/configurable/dsl.rb:31:in `setting'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-configurable-0.16.1/lib/dry/configurable/class_methods.rb:44:in `setting'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.18.1/lib/dry/system/container.rb:75:in `<class:Container>'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.18.1/lib/dry/system/container.rb:68:in `<module:System>'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.18.1/lib/dry/system/container.rb:24:in `<module:Dry>'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/dry-system-0.18.1/lib/dry/system/container.rb:23:in `<top (required)>'
  /home/bl1ndy/projects/todo_api/system/application.rb:4:in `require'
  /home/bl1ndy/projects/todo_api/system/application.rb:4:in `<top (required)>'
  /home/bl1ndy/projects/todo_api/Rakefile:3:in `require_relative'
  /home/bl1ndy/projects/todo_api/Rakefile:3:in `<top (required)>'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
  /home/bl1ndy/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
  /home/bl1ndy/.rbenv/versions/3.1.2/bin/rake:25:in `load'
  /home/bl1ndy/.rbenv/versions/3.1.2/bin/rake:25:in `<main>'
```
</details>

My Gemfile is

<details>

```
# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.1.2'

gem 'activesupport'
gem 'bcrypt'
gem 'dry-system', '0.18.1'
gem 'dry-validation'
gem 'i18n'
gem 'oj'
gem 'pry'
gem 'puma', '~> 5.6', '>= 5.6.5'
gem 'rake'
gem 'roda', '~> 3.62'
gem 'roda-enhanced_logger', '~> 0.5.0'
gem 'sequel', '~> 5.63'
gem 'sequel_pg', '~> 1.17'
gem 'sequel_secure_password'
gem 'timecop'
gem 'yard'

group :development, :test do
  gem 'dotenv'
  gem 'factory_bot'
  gem 'rack-test'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'rubocop-sequel'
  gem 'rubocop-thread_safety'
end
```
</details>

**Comment by MatUrbanski** [comment]
Hello, please try the following version of dry-system:

```
gem 'dry-system', '0.19.1'

```

**Comment by bl1ndy** [comment]
> Hello, please try the following version of dry-system:
> 
> ```
> gem 'dry-system', '0.19.1'
> ```

Already tried. Same error :(

**Comment by bl1ndy** [comment]
So, I cloned your repository and everything starts correctly. Probably need to compare versions in Gemfile.lock files.
